version: '3.8'

services:
    db:
    image: mysql:latest
    container_name: my_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network

  app:
    build:
      context: .
    container_name: my_app
    restart: always
    environment:
      DB_HOST: db
      DB_USER: my_user
      DB_PASSWORD: my_password
      DB_NAME: my_database
      DB_PORT: 3306
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
    driver: bridge